---
- name: Ensure EPEL repo is installed
  include: epel.yml

- name: Update all packages and reboot
  include: update.yml

- name: Ensure required packages are installed
  include: yum.yml

- name: Ensure required Python packages are installed
  include: python.yml

- name: Ensure Docker is properly installed
  include: docker.yml
