---
- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: "epel"
  register: update_system

- name: Reboot if state changed
  shell: sleep 2 && shutdown -r now 'System update reboot'
  async: 1
  poll: 0
  ignore_errors: true
  when: update_system.changed

- pause:
    seconds: 30
  when: update_system.changed

- name: Waiting for hosts to be available
  local_action: wait_for host="{{ ansible_default_ipv4.address }}" search_regex=OpenSSH port=22 timeout=300
  become: false
  when: update_system.changed
